name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.5'
          distribution: 'temurin' # Adoptium est maintenant appelé Temurin dans les distributions
          
      - name: Install Dependencies
        run: |
          mvn install:install-file -Dfile=TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
          mvn install:install-file -Dfile=TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
          mvn install:install-file -Dfile=TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
          
      - name: Build with Maven
        run: mvn -B clean install # L'option -B est pour le mode batch (non interactif)
      
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: app-jar
          path: tourguide/target/*.jar

